version: "3.3"
services:
  sqlservers:
    image: "mcr.microsoft.com/mssql/server"
    user: root
    volumes:
      - sqlservers-data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "@Daneshgah65411887"
      ACCEPT_EULA: "Y"
    restart: always
  webapplication:
    build:
      context: .
      dockerfile: ./src/Presentation/WebApplication/Dockerfile
    depends_on:
      - sqlservers
    ports:
      - "8080:80"
    restart: always
    environment:
      - DBHOST=sqlservers
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  sqlservers-data:
